# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: build

  git-submodules:
    status:
      - test -f "{{ joinPath .TASKFILE_DIR "libs" "xenon" ".gitignore" }}"
    cmds:
      - git add .
      - git submodule update --init --recursive

  build:
    deps: [git-submodules]
    vars:
      GRADLEW_FILENAME: '{{ if eq OS "windows" }}gradlew.bat{{ else }}gradlew{{ end }}'
      RUN: '{{ if eq OS "windows" }}cmd /D /E:ON /C{{ else }}bash -c{{ end }}'
    cmds:
      - cmd: |
          {{.RUN}} call "{{ joinPath .TASKFILE_DIR .GRADLEW_FILENAME }}" build

  db:
    cmds:
      - cmd: docker-compose up -d db

  stop-db:
    cmds:
      - cmd: docker-compose stop db

  test:
    deps: [db]
    cmds:
      - cmd: export POSTGRES_USER=postgres && export POSTGRES_PASSWORD=postgres && export POSTGRES_URL=localhost:5432/postgres && mvn test;

  publish:
    cmds:
      - cmd: mvn -DskipTests clean deploy
